using AffiseAttributionLib;
using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;

public class AffiseDebugger : MonoBehaviour
{
    [SerializeField] private TextMeshProUGUI refText;
    [SerializeField] private TextMeshProUGUI isInitText;
    void Start()
    {
        StartCoroutine(WaitBeforShow());
        isInitText.text = "IsInit: " + Affise.IsInit.ToString();
        Debug.Log(isInitText.text);
    }

    IEnumerator WaitBeforShow()
    {
        yield return new WaitForSecondsRealtime(15f);
        refText.text = "Referrer: " + Affise.GetReferrer();
        Debug.Log(refText.text);
    }
}
